import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { LanguageProvider } from '../frontend/src/i18n';
import { ResultDetail } from '../frontend/src/views/Factors';
import { FactorCollection } from '../frontend/src/components/FactorCollection';
import { FactorIntro, minuteTime } from '../frontend/src/components/FactorIntro';
import { linePath } from '../frontend/src/components/PerformanceChart';
import { candleBuckets, boundDomain } from '../frontend/src/components/chart-window';
import { OhlcChart } from '../frontend/src/components/OhlcChart';
import { Database } from '../frontend/src/views/Database';
import type { DatabaseOverview, ResearchCatalog, ResearchResults } from '../frontend/src/types';

Object.assign(globalThis, { window: { matchMedia: () => ({ matches: true }) }, localStorage: { getItem: () => 'en' } });
const fixture = JSON.parse(readFileSync(process.env.RECIPE_CHECK_FIXTURE!, 'utf8')) as {catalog: ResearchCatalog; results: ResearchResults[]; database: DatabaseOverview};
const wrap = (node: React.ReactNode) => renderToStaticMarkup(<LanguageProvider>{node}</LanguageProvider>);
const noop = () => {};
const chinese = /[\u3400-\u9fff]+/g;
const missing = new Set<string>();
for (const result of fixture.results) {
  const markup = wrap(<ResultDetail result={result} catalog={fixture.catalog} onSelect={noop} onBack={noop} onIntro={noop}/>);
  const text = markup.replace(/<[^>]+>/g, '');
  for (const item of text.match(chinese) ?? []) missing.add(item);
  assert(markup.includes('<math'));
  assert(markup.includes('Asia/Shanghai'));
  assert(!markup.includes('type="date"'));
  assert(!markup.includes('NaN'));
  const intro = wrap(<FactorIntro strategy={result.strategy} onEnter={noop} onBack={noop}/>);
  for (const item of intro.replace(/<[^>]+>/g, '').match(chinese) ?? []) missing.add(item);
}
const collection = wrap(<FactorCollection strategies={fixture.catalog.strategies} onSelect={noop}/>);
assert.equal((collection.match(/class="orbit-factor-card"/g) ?? []).length, 4);
for (const item of collection.replace(/<[^>]+>/g, '').match(chinese) ?? []) missing.add(item);
const database = wrap(<Database initialSnapshot={fixture.database}/>);
assert(database.includes('Database Management'));
assert(database.includes('Data version &amp; recent changes'));
assert(database.includes('FILES IN MANIFEST'));
assert.equal((database.match(/class="db-pipe(?: |")/g) ?? []).length, fixture.database.domains.length);
assert.equal((database.match(/class="db-pipe-liquid"/g) ?? []).length, fixture.database.domains.length);
assert.equal((database.match(/class="db-pipe is-live"/g) ?? []).length, 1);
assert(database.includes('class="room-keeper'));
assert(!database.includes('Business quality'));
for (const item of database.replace(/<[^>]+>/g, '').match(chinese) ?? []) missing.add(item);
assert.equal(minuteTime('2026-09-07T21:05:42'), '2026-09-07 21:05');
assert.equal(linePath([{x: 0, y: 1}, {x:1, y: null}, {x:2,y:3}, {x:3,y:4}]), 'M0.00,1.00M2.00,3.00L3.00,4.00');
const bars = Array.from({length: 40}, (_, i) => ({ts:`2026-09-03T09:${String(i).padStart(2,'0')}:00`,open:100+i,high:102+i,low:99+i,close:101+i,volume:100,amount:10000,open_interest:200,contract:'AU2612',product_id:'SHFE.AU'}));
const aggregated = candleBuckets(bars, 0, bars.length, 4);
assert.equal(aggregated.length, 4);
assert.equal(aggregated[0].bar.open, bars[0].open);
assert.equal(aggregated[0].bar.close, bars[9].close);
assert.equal(aggregated[0].bar.high, bars[9].high);
assert.equal(aggregated[0].bar.low, bars[0].low);
assert.equal(aggregated[0].bar.volume, 1000);
assert.deepEqual(boundDomain(-8, 12, 40), {start: 0, end: 20});
assert.deepEqual(boundDomain(30, 50, 40), {start: 20, end: 40});
for (const daily of [false,true]) { const markup = wrap(<OhlcChart bars={bars} daily={daily}/>); assert(!markup.includes('NaN')); assert(markup.includes('AU2612')); }
assert.deepEqual([...missing], [], 'English mode must translate every visible research string');
console.log('SSR checks passed: database pipelines, 7 results + 7 architecture intros, 4 orbit cards, English coverage, math, minute timestamps, OHLC rendering and curve gaps.');
